"""add requested_by_id to appointment

Revision ID: f85919028770
Revises: df4eda0b3741
Create Date: 2025-06-05 07:08:51.287260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85919028770'
down_revision: Union[str, None] = 'df4eda0b3741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('requested_by_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'requested_by_id')
    # ### end Alembic commands ###
